/**
 * audit-submitter.ts — Submit an EZKL audit bundle to PerformanceOracle.
 *
 * Loads the bundle.json + feed.json that prove.py wrote and packs them into
 * the AuditSubmission struct expected by PerformanceOracle.submitAudit.
 *
 * KNOWN LIMITATIONS (to be lifted by future tasks, not blocking F1's TS plumbing):
 *   1. PerformanceOracle.sol currently uses single-sibling Merkle proofs per bar.
 *      The audit window from prove.py has many bars, so feed.siblings_per_bar
 *      contains multi-level paths. We only emit the FIRST sibling per bar here,
 *      which means the on-chain Merkle check will only succeed for 2-leaf trees.
 *      A multi-level Merkle extension to the oracle is required for the full
 *      32+-bar audit window to verify on chain.
 *   2. The Halo2 verifier auto-generated by EZKL expects the model's input/
 *      output sample data as public inputs, while the contract's submitAudit
 *      requires (modelWeightsHash, outputsHash, priceFeedRoot). Bridging this
 *      requires a custom EZKL circuit that exposes those hashes as public
 *      inputs; out of scope for F1.
 */
import { ethers } from "ethers";
import fs         from "fs";
import path       from "path";

export interface AuditBundle {
  epoch:               number;
  merkle_root:         string;       // "0x..." 32-byte hex
  outputs:             number[][];   // (n_rows, NUM_TOKENS) softmax weights, floats in [0,1]
  proof_path:          string;       // path to ezkl proof.json
  vk_path:             string;
  verifier_sol_path:   string;
  settings_path:       string;
}

export interface FeedJson {
  epoch:            number;
  merkle_root:      string;          // "0x..."
  bars:             number[];        // length n_bars; basket-mean prices (int, 1e8 scale)
  indexes:          number[];        // length n_bars; flat Merkle leaf index
  siblings_per_bar: string[][];      // length n_bars; each entry is a Merkle path (hex bytes32 strings)
}

/**
 * Build the AuditSubmission tuple the contract expects.
 */
export function packSubmission(args: {
  tokenId:          bigint;
  modelWeightsHash: string;          // "0x..." 32-byte hex
  bundle:           AuditBundle;
  feed:             FeedJson;
}) {
  const { tokenId, modelWeightsHash, bundle, feed } = args;

  // outputs are softmax floats; on-chain we use int256 in bps. Match the
  // training/backtest convention: round each weight to int bps (sum ~ 10_000).
  const outputsFlat: bigint[] = [];
  for (const row of bundle.outputs) {
    for (const v of row) outputsFlat.push(BigInt(Math.round(v * 10_000)));
  }
  const outputsHash = ethers.keccak256(
    ethers.solidityPacked(["int256[]"], [outputsFlat]),
  );

  const publicInputs = [
    BigInt(modelWeightsHash),
    BigInt(outputsHash),
    BigInt(feed.merkle_root),
  ];

  // EZKL writes proof.json with a `hex_proof` field (the on-chain bytes) and
  // a parallel `proof` field that's a byte array — we want the hex one.
  const proofJson = JSON.parse(fs.readFileSync(bundle.proof_path, "utf8"));
  const rawHex: string =
    typeof proofJson.hex_proof === "string" ? proofJson.hex_proof :
    typeof proofJson.proof     === "string" ? proofJson.proof     :
    Array.isArray(proofJson.proof)          ? "0x" + Buffer.from(proofJson.proof).toString("hex") :
    (() => { throw new Error("proof.json: no recognizable proof field"); })();
  const proofBytes = rawHex.startsWith("0x") ? rawHex : "0x" + rawHex;

  // Single-sibling Merkle: take siblings_per_bar[i][0] for each bar. Limitation
  // documented at top of file.
  const siblings = feed.siblings_per_bar.map(path => {
    if (path.length === 0) return ethers.ZeroHash;
    const s = path[0];
    return s.startsWith("0x") ? s : "0x" + s;
  });

  // priceFeedBars / priceFeedIndexes lengths must match outputs.length.
  // outputs is (n_rows, NUM_TOKENS); contract iterates outputs.length and
  // expects bars/indexes of the same length.
  const flatOutputsLen = outputsFlat.length;

  return {
    tokenId,
    epoch:             BigInt(bundle.epoch),
    modelWeightsHash,
    outputsHash,
    outputs:           outputsFlat,
    publicInputs,
    snarkProof:        proofBytes,
    priceFeedSiblings: siblings.slice(0, flatOutputsLen),
    priceFeedIndexes:  feed.indexes.slice(0, flatOutputsLen).map(i => BigInt(i)),
    priceFeedBars:     feed.bars.slice(0, flatOutputsLen).map(v => BigInt(v)),
  };
}

/**
 * Submit a packed audit on chain. Throws on revert; returns the tx hash on success.
 */
export async function submitAudit(args: {
  oracle:           ethers.Contract;
  tokenId:          bigint;
  modelWeightsHash: string;
  bundle:           AuditBundle;
  feed:             FeedJson;
}): Promise<string> {
  const sub = packSubmission(args);
  const tx  = await args.oracle.submitAudit(sub);
  const rcpt = await tx.wait();
  return rcpt.hash;
}

/**
 * Convenience: read both JSONs from a prove.py output directory.
 */
export function loadProofArtifacts(proofDir: string): { bundle: AuditBundle; feed: FeedJson } {
  const bundle = JSON.parse(fs.readFileSync(path.join(proofDir, "bundle.json"), "utf8")) as AuditBundle;
  const feed   = JSON.parse(fs.readFileSync(path.join(proofDir, "feed.json"),   "utf8")) as FeedJson;
  return { bundle, feed };
}
